swagger: "2.0"
info:
  version: "0.1.0"
  title: Quests API service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /map:
    # binds a127 app logic to a route
    x-swagger-router-controller: map
    get:
      description: Returns some info about map
      # used as the method name of the controller
      operationId: map
      parameters:
        - name: parametres
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definitiony
            $ref: "#/definitions/MapResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /genre:
    # binds a127 app logic to a route
    x-swagger-router-controller: genre
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: genre
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenreResponse"    
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  
  /reviews:
    # binds a127 app logic to a route
    x-swagger-router-controller: reviews
    get:
      description: Returns some info about review
      # used as the method name of the controller
      operationId: reviews
      parameters:
        - name: parametres
          in: query
          #description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definitiony
            $ref: "#/definitions/ReviewsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /main:
    # binds a127 app logic to a route
    x-swagger-router-controller: main
    get:
      description: Returns parametres of Quests
      # used as the method name of the controller
      operationId: main

      parameters:
        - name: parametres
          in: query
          #description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definitiony
            $ref: "#/definitions/QuestsResponse"

            
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  MapResponse:
    type: array
    items: 
      $ref: "#/definitions/Map"
      
  Map: 
    properties: 
      name: 
        type: string
      genre: 
        type: string
      coorX: 
        type: string
      coorY: 
        type: string  
      

  ReviewsResponse:
    type: array
    items:
      $ref: "#/definitions/Reviews"
      
  Reviews:
    properties:
      name:
        type: string
      lastName:
        type: string
      image:
        type: string
      review:
        type: string
      date:
        type: string
  
  QuestsResponse:
    type: array
    items:
      $ref: "#/definitions/Quests"
  Quests: 
    required:
      - id
    properties:
      id: 
        type: string
      name: 
        type: string
      genre:
        type: string
      image: 
        type: string
      definition:
        type: string
        
  GenreResponse:
    type: array
    items:
      $ref: "#/definitions/Genre"
  Genre:
    properties:
      genre:
        type: string
      name:
        type: string
      image:
        type: string
      id:
        type: string
      description:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
